#Common Configuration Parameters
gem_left_foot_wrench_topic: "/xbotcore/cogimon/ft/l_leg_ft"  #left foot FT
gem_right_foot_wrench_topic: "/xbotcore/cogimon/ft/r_leg_ft" #right foot FT
gem_freq: 200    #min freq of all topics
gem_lfoot_frame: "l_ankle"   #left foot frame 
gem_rfoot_frame: "r_ankle"   #right foot frame 

#Unsupervisead Gait Phase Learning Parameters
useUL: False  #Use Unsupervised Learning (Dimensionality Reduction + Clustering) for  Gait Phase Estimation
#Only if use_UL is True
gem_imu_topic: "/xbotcore/cogimon/imu/imu_link" # base_link (body) IMU
gem_com_topic: "/SERoW/rel_CoM/pose"  #relative to base_link (body) CoM - computed with kinematics
gem_cf: True #use complimentary filtering if orientation is not provided in IMU topic
gem_cf_a : 0.999  #complimentary filter parameter alpha
gem_plot_results: True #plot the results only works when Dimensionality Reduction is performed
gem_dim: 2
gem_gt_comparison: False  #compare to ground-truth, to do so user must supply true friction coefficient mu and ground reaction forces and torques.
gem_save: True  #Save the Training Results to load in real-time
gem_dim_reduction: "autoencoders" #autoencoders or pca supported at the current time
gem_clustering: "gmm" #gmm or kmeans supported at the current time
gem_train_path: "/Users/ownage/Desktop/gem/src/GEM_test_cogimon_gem" #path to training data, data must have same(or approx. same) sampling rate e.g. gem_freq.
gem_lfoot_torque_bias: [0, 0, 0] #left foot FT bias  
gem_lfoot_force_bias: [0,0, 0] 
gem_rfoot_torque_bias: [0, 0, 0] #right foot FT bias 
gem_rfoot_force_bias: [0,0,0]

#Custom Gait Phase Estimation Parameters if no learning was performed
#Only if use_UL is False
useCOP: True  #Use the full contact wrench in the detection process
gem_foot_xmax: 0.1136       #Foot Polygon xmax
gem_foot_xmin: -0.1564      #Foot Polygon xmin
gem_foot_ymax: 0.135        #Foot Polygon ymax
gem_foot_ymin: -0.135       #Foot Polygon ymin
gem_lfoot_force_thres: 25   #left foot contact thres 
gem_rfoot_force_thres: 25   #right foot contact thres 
gem_lforce_std: 2.2734      #left foot force standard deviation
gem_rforce_std: 5.6421      #right foot force standard deviation
gem_lcop_std: 0.005         #left foot COP standard deviation
gem_rcop_std: 0.005         #right foot COP standard deviation
useKin: False #Use differential kinematic information in the detection process
gem_lfoot_vel_topic: "/SERoW/LLeg/vel"
gem_rfoot_vel_topic: "/SERoW/RLeg/vel"
gem_lfoot_vel_std: 0.05
gem_rfoot_vel_std: 0.05
gem_lfoot_vel_thres: 0.1
gem_rfoot_vel_thres: 0.1